const Map<String, String> ar = {
  'login': 'تسجيل الدخول',
  "nodata": "لا يوجد بيانات",
  'useremail': 'الايميل',
  'userpassword': 'كلمة المرور',
  'forgetpassword': 'نسيت كلمة المرور',
  'welcomtothefarm': 'مرحبا بك فى المزرعة',
  "information": "معلومات عنا",
  "feedback": "ملاحظات",
  'Hello in Plantera': 'مرحبا فى Plantera',
  'thefarmer': 'المزرعة',
  "test": "تجربة",
  "info":
      "هذا البرنامج هو نظام مزرعة ذكي للعناية بالمصنع من خلال معرفة رطوبة الهواء ودرجة الحرارة ورطوبة التربة. إذا كانت الرطوبة منخفضة لمصنع معين ، فإن المحرك المائي يمر عبر نظام الري الذكي حتى يصل إلى الرطوبة المطلوبة. يمكن أيضًا التنبؤ بكمية المحاصيل المنتجة في كل موسم. إذا كان النبات مريضًا أم لا ، من خلال نموذج التعلم الآلي واقتراح العلاج. يتم الوصول إلى البرنامج عبر رسالة بريد إلكتروني يأخذها المستخدم من الشركة المسؤولة عن المشروع. يمكن الاتصال بنا عبر صفحة الويب.",
  'myfarm': 'مزرعتى',
  'farms': 'المزارع',
  'detect': 'اكتشاف المرض',
  'menu': 'القائمة',
  'acount': 'الحساب',
  'setting': 'الاعدادات',
  'help': 'مساعدة',
  'camera': 'الكاميرا',
  'device': 'المعرض',
  'upload': 'معرفة المرض',
  'farm1': 'مزرعة 1',
  'farm2': 'مزرعة 2',
  'farm3': 'مزرعة 3',
  'farm4': 'مزرعة 4',
  'farm5': 'مزرعة 5',
  'farm6': 'مزرعة 6',
  'farm7': 'مزرعة 7',
  'farm8': 'مزرعة 8',
  'farm9': 'مزرعة 9',
  'farm10': 'مزرعة 10',
  'farm11': 'مزرعة 11',
  'farm12': 'مزرعة 12',
  'temperature': 'درجة الحرارة',
  'airhumidity': 'رطوبة الجو',
  'soilmoisture': 'رطوبة التربة',
  'predictgrowth': 'توقع المحصول',
  'acountinfo': 'معلومات الحساب',
  'username': 'الايميل',
  'password': 'كلمة المرور',
  'phone': 'رقم الهاتف',
  'location': 'الموقع',
  'logout': 'تسجيل خروج',
  'myprofile': 'حسابى',
  'language': 'اللغة',
  'darkmode': 'الوضع الداكن',
  "tomatoes": 'طماطم',
  "potatoes": 'بطاطس',
  "lettuce": "خص",
  "corn": "ذرة",
  "switch": "تحويل",
  "carrots": "جزر",
  "selectedone": "اختار واحدة",
  "selected language": "اللغة",
  'selectedplat': 'اختار نبتة',
  'withemail': 'بالبريد الإلكتروني',
  'withphonenumber': ' برقم الهاتف',
  'makeselection!': ' الاختيار!',
  'selectoneoftheoptiongivenbelowtoresetyourpassword':
      'حدد أحد الخيارات الواردة أدناه لإعادة تعيين كلمة المرور الخاصة بك',
  'next': 'التالى',
  'email': 'الايميل',
  'back': 'الرجوع',
  'wehavesentyouemailtorecoverpassword':
      'لقد أرسلنا لك بريدًا إلكترونيًا لاستعادة كلمة المرور',
  'pleasecheckyouremail': ' يرجى التحقق من بريدك الإلكترونى',
  'thereiserrorinyouremail': 'هناك خطأ فى حسابك',
  'Sucessfulllogin': 'تسجيل ناجح',
  'Hi': 'اهلا ',
  'usernameunknown': 'اسم المستخدم غير معروف',
  'tryanthorone': 'جرب واحدة أخرى',
  'resetpassword': 'إعادة تعيين كلمة المرور',
  "wait": "انتظار",
  "loading": "....انتظر",
  "change": "تغيير",
  'textformisempty': 'الصندوق فارغ',
  'youshouldwriteanumber': 'يجب ان تكتب رقم',
  "acidity": " حموضةالتربة",
  "fertilizer": " السماد",
  "passwordunknown": "الباسورد خاطئ",
  "It will rany today": "انها تمطر",
  'thenumberisoutofrange': 'الرقم خارج النطاق المحدد',
  'youshouldwriteanumber<100': 'الرقم يجب ان يكون [0:100]',
  'youshouldwriteanumber<14': 'الرقم يجب ان يكون [0:14]',
  "disease is : ": "المرض : ",
  'Apple___Apple_scab': 'جرب التفاح',
  'Apple___Black_rot': 'تعفن أسود (تفاح)',
  'Apple___Cedar_apple_rust': 'صدأ التفاح والارز',
  'Apple___healthy': 'التفاح صحي',
  'Blueberry___healthy': 'توت صحي',
  'Cherry_(including_sour)___Powdery_mildew':
      '(بما في ذلك الكرز الحامض) البياض الدقيقي',
  'Cherry_(including_sour)___healthy': '(بما في ذلك الكرز الحامض) صحي',
  'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot':
      'بقعة الأوراق بقعة الأوراق الرمادية (الذرة)',
  'Corn_(maize)__Common_rust': 'صدأ الذرة الشائع',
  'Corn_(maize)___Northern_Leaf_Blight': 'لفحة أوراق الذرة الشمالية',
  'Corn_(maize)___healthy': 'الذرة صحية',
  'Grape___Black_rot': 'تعفن العنب الأسود',
  'Grape___Esca_(Black_Measles)': 'حصبة سوداء (عنب)',
  'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)':
      'لفحة أوراق العنب (بقعة أوراق إيزاريوبسيس)',
  'Grape___healthy': 'عنب صحي',
  'Orange___Haunglongbing_(Citrus_greening)': 'تخضير الحمضيات (برتقالي)',
  'Peach___Bacterial_spot': 'بقعة الخوخ البكتيرية',
  'Peach___healthy': 'خوخ صحي',
  'Pepper,_bell___Bacterial_spot': 'بقعة بكتيرية (فلفل)',
  'Pepper,_bell___healthy': 'فلفل صحي',
  'Potato___Early_blight': 'اللفحة المبكرة (البطاطس)',
  'Potato___Late_blight': 'اللفحة المتأخرة (البطاطس)',
  'Potato___healthy': 'البطاطس صحية',
  'Raspberry___healthy': 'التوت صحي',
  'Soybean___healthy': 'فول الصويا صحي',
  'Squash___Powdery_mildew': 'البياض الدقيقي (قرع)',
  'Strawberry___Leaf_scorch': 'حرق أوراق الفراولة',
  'Strawberry___healthy': 'الفراولة صحية',
  'Tomato___Bacterial_spot': 'بقعة بكتيرية (طماطم)',
  'Tomato___Early_blight': 'اللفحة المبكرة (طماطم)',
  'Tomato___Late_blight': 'اللفحة المتأخرة (طماطم)',
  'Tomato___healthy': 'الطماطم صحية',
  'Tomato___Leaf_Mold': 'قالب أوراق الطماطم',
  'Tomato___Septoria_leaf_spot': 'بقعة أوراق الطماطم',
  'Tomato___Spider_mites Two-spotted_spider_mite':
      'سوس العنكبوت ذو النقطتين (الطماطم)',
  'Tomato___Target_Spot': 'بقعة الهدف (طماطم)',
  'Tomato___Tomato_Yellow_Leaf_Curl_Virus': 'فيروس تجعد أوراق الطماطم الصفراء',
  'Tomato___Tomato_mosaic_virus': 'فيروس فسيفساء الطماطم',
  "null": "انتظر....",
  "you have an error": "لديك خطأ",
  "know_the_treatment": "العلاج",
  "Warm wet conditions favour the disease such that fungicides are needed to give adequate control. The products to use are chlorothalonil, copper oxychloride or mancozeb. Treatment should start when the first spots are seen and continue at 10-14-day intervals until 3-4 weeks before last harvest.":
      "تفضل الظروف الرطبة الدافئة المرض بحيث تكون هناك حاجة لمبيدات الفطريات لإعطاء السيطرة الكافية. المنتجات التي يجب استخدامها هي كلوروثالونيل ، أوكسي كلوريد النحاس أو مانكوزيب. يجب أن يبدأ العلاج عند ظهور البقع الأولى ويستمر كل 10-14 يومًا حتى 3-4 أسابيع قبل آخر حصاد.",
  "Fungicides. Foliar fungicides may be applied early in the growing season to corn seedlings as a risk-management tool for northern corn leaf blight and other corn diseases, including anthracnose leaf blight and corn eyespot.":
      "مبيدات الفطريات. يمكن استخدام مبيدات الفطريات الورقية في وقت مبكر من موسم النمو على شتلات الذرة كأداة لإدارة مخاطر لفحة أوراق الذرة الشمالية وأمراض الذرة الأخرى ، بما في ذلك لفحة أوراق الأنثراكنوز وبقعة عين الذرة.",
  "Home gardeners who remove all fallen leaves from under their apple trees should experience good control of apple scab. Leaves may be safely composted. Foliar application of a 5% urea solution in autumn just before leaf drop will speed natural decomposition of leaves and help to deactivate the scab fungus.":
      "يجب أن يتمتع البستانيون الذين يزيلون جميع الأوراق المتساقطة من تحت أشجار التفاح بالتحكم الجيد في جرب التفاح. يمكن تحويل الأوراق إلى سماد بأمان. يؤدي تطبيق محلول اليوريا بنسبة 5٪ على الأوراق في الخريف قبل تساقط الأوراق مباشرة إلى تسريع التحلل الطبيعي للأوراق ويساعد على إبطال نشاط فطر الجرب.",
  "Fungicides with the active ingredient Myclobutanil are most effective in preventing rust. Copper and sulfur products can be used as well. Spray trees and shrubs when flower buds first emerge until spring weather becomes consistently warm and dry.":
      "تعتبر مبيدات الفطريات التي تحتوي على العنصر النشط Myclobutanil أكثر فعالية في منع الصدأ. يمكن أيضًا استخدام منتجات النحاس والكبريت. رش الأشجار والشجيرات عندما تظهر براعم الزهور لأول مرة حتى يصبح طقس الربيع دافئًا وجافًا باستمرار.",
  "Remove and destroy all affected plant parts. For plants growing under cover, increase ventilation and, if possible, the space between plants. Try to avoid wetting the leaves when watering plants, especially when watering in the evening, Copper-based fungicides can be used to control diseases on tomatoes.":
      "قم بإزالة وتدمير جميع أجزاء النبات المصابة. بالنسبة للنباتات التي تنمو تحت الغطاء ، قم بزيادة التهوية ، وإذا أمكن ، المسافة بين النباتات. حاول تجنب ترطيب الأوراق عند سقي النباتات ، خاصة عند الري في المساء ، يمكن استخدام مبيدات الفطريات المحتوية على النحاس للسيطرة على الأمراض التي تصيب الطماطم.",
  "Captan and sulfur products are labeled for control of both scab and black rot. A scab spray program including these chemicals may help prevent the frog-eye leaf spot of black rot, as well as the infection of fruit. These sprays will not control or prevent infection of branches.":
      "يتم تصنيف منتجات الكبتان والكبريت للتحكم في كل من الجرب والتعفن الأسود. قد يساعد برنامج رذاذ الجرب بما في ذلك هذه المواد الكيميائية في منع بقعة أوراق عين الضفدع من العفن الأسود، وكذلك عدوى الفاكهة. لن تتحكم هذه البخاخات في عدوى الفروع أو تمنعها.",
  "Powdery mildew is managed through a combination of fungicides, starting from petal fall and continuing through pit hardening, and the use of resistant varieties. Many fungicides used for brown rot control are effective against powdery mildew.":
      "تتم إدارة مسحوق العفن من خلال مزيج من مبيدات الفطريات، بدءًا من سقوط البتلات واستمرارها من خلال تصلب الحفرة واستخدام الأصناف المقاومة. العديد من مبيدات الفطريات المستخدمة للتحكم في العفن البني فعالة ضد مسحوق العفن.",
  "During the growing season, foliar fungicides can be used to manage gray leaf spot outbreaks. Farmers must consider the cost of the application and market value of their corn before determining if fungicides will be an economical solution to GLS":
      "خلال موسم النمو، يمكن استخدام مبيدات الفطريات الورقية لإدارة تفشي الأوراق الرمادية. يجب على المزارعين النظر في تكلفة تطبيق الذرة وقيمتها السوقية قبل تحديد ما إذا كانت مبيدات الفطريات ستكون حلاً اقتصاديًا لـ GLS",
  "The best management practice is to use resistant corn hybrids. Fungicides can also be beneficial, especially if applied early when few pustules have appeared on the leaves.":
      "أفضل ممارسة للإدارة هي استخدام هجينة الذرة المقاومة. يمكن أن تكون مبيدات الفطريات مفيدة أيضًا، خاصةً إذا تم وضعها مبكرًا عندما تظهر بثور قليلة على الأوراق.",
  "Hot water treatment at 122°F for 25 min is effective in reducing bacterial population on the surface and inside the seeds, but may affect seed germination when the temperature is not properly controlled. Rinse seed in clean water immediately after treatments. The seed should be air dried prior to storing.":
      "تعتبر معالجة المياه الساخنة عند 122 درجة فهرنهايت لمدة 25 دقيقة فعالة في تقليل عدد البكتيريا على السطح وداخل البذور، ولكنها قد تؤثر على إنبات البذور عندما لا يتم التحكم في درجة الحرارة بشكل صحيح. اشطف البذور في المياه النظيفة فور العلاج. يجب تجفيف البذور بالهواء قبل التخزين.",
  "Treatment. Tomatoes that have early blight require immediate attention before the disease takes over the plants. Thoroughly spray the plant (bottoms of leaves also) with Bonide Liquid Copper Fungicide concentrate or Bonide Tomato & Vegetable. Both of these treatments are organic.":
      "العلاج. تتطلب الطماطم التي تعاني من آفة مبكرة اهتمامًا فوريًا قبل أن يسيطر المرض على النباتات. قم برش النبات جيدًا (قيعان الأوراق أيضًا) مع مبيد الفطريات النحاسي السائل بونيد أو بونيد الطماطم والخضروات. كل من هذه العلاجات عضوية.",
  "Spraying fungicides is the most effective way to prevent late blight. For conventional gardeners and commercial producers, protectant fungicides such as chlorothalonil (e.g., Bravo, Echo, Equus, or Daconil) and Mancozeb (Manzate) can be used.":
      "رش مبيدات الفطريات هو الطريقة الأكثر فعالية لمنع الآفة المتأخرة. بالنسبة للبستانيين التقليديين والمنتجين التجاريين، يمكن استخدام مبيدات الفطريات الحمائية مثل الكلوروثالونيل (على سبيل المثال، برافو، إيكو، إيكوس، أو داكونيل) ومانكوزيب (مانزات).",
  "Fungicides are very effective for control of Septoria leaf spot and applications are often necessary to supplement the control strategies previously outlined. The fungicides chlorothalonil and mancozeb are labeled for homeowner use":
      "تعتبر مبيدات الفطريات فعالة للغاية للتحكم في بقعة أوراق سبتوريا وغالبًا ما تكون التطبيقات ضرورية لاستكمال استراتيجيات المراقبة الموضحة سابقًا. تم تصنيف مبيدات الفطريات كلوروثالونيل والمانكوزيب لاستخدام صاحب المنزل",
  "make 2 applications, approximately 5-7 days apart, to help control immature mites that were in the egg stage and protected during the first application. Alternate between products after 2 applications to help prevent or delay resistance.":
      "إجراء تطبيقات 2، تفصل بينها 5-7 أيام تقريبًا، للمساعدة في السيطرة على العث غير الناضج الذي كان في مرحلة البيض ومحميًا أثناء التطبيق الأول. البديل بين المنتجات بعد التطبيقات 2 للمساعدة في منع أو تأخير المقاومة.",
  "There is no treatment against TYLCV. Control the whitefly population to avoid the infection with the virus.":
      "لا يوجد علاج ضد TYLCV. السيطرة على مجموعة الذبابة البيضاء لتجنب الإصابة بالفيروس.",
  "Remove all infected plants and destroy them. Do NOT put them in the compost pile, as the virus may persist in infected plant matter. Burn infected plants or throw them out with the garbage. Monitor the rest of your plants closely, especially those that were located near infected plants.":
      "إزالة جميع النباتات المصابة وتدميرها. لا تضعها في كومة السماد، حيث قد يستمر الفيروس في المادة النباتية المصابة. حرق النباتات المصابة أو رميها بالقمامة. راقب عن كثب بقية نباتاتك، خاصة تلك التي كانت موجودة بالقرب من النباتات المصابة.",
  "Remove infected fruit as it is discovered during the growing season. Fungicide application: Correct timing of fungicide application is critical to effective management of black rot because most fungicide are preventative. Apply protectant fungicides from shortly before bloom through 4 weeks after bloom.":
      "قم بإزالة الفاكهة المصابة كما يتم اكتشافها خلال موسم النمو. تطبيق مبيدات الفطريات: التوقيت الصحيح لتطبيق مبيدات الفطريات أمر بالغ الأهمية للإدارة الفعالة للعفن الأسود لأن معظم مبيدات الفطريات وقائية. ضع مبيدات الفطريات الواقية من قبل فترة وجيزة من الازدهار خلال 4 أسابيع بعد الإزهار.",
  "Soak dormant cuttings for 30 mins in hot water at about 50°C. This treatment is not always effective and must therefore be combined with other methods. Some species of Trichoderma have been used to prevent the infection of pruning wounds, basal ends of propagation material, and graft unions.":
      "انقع القصاصات الخاملة لمدة 30 دقيقة في الماء الساخن عند حوالي 50 درجة مئوية. هذا العلاج ليس فعالا دائما وبالتالي يجب أن يقترن مع طرق أخرى. تم استخدام بعض أنواع Trichoderma لمنع عدوى جروح التقليم، والنهايات القاعدية لمواد الانتشار، واتحادات الطعم.",
  "Spraying of the grapevines at 3-4 leaf stage with fungicides like Bordeaux mixture @ 0.8% or Copper Oxychloride @ 0.25% or Carbendazim @ 0.1% are effective against this disease.":
      "رش العنب في مرحلة 3-4 أوراق بمبيدات الفطريات مثل خليط بوردو @ 0.8٪ أو النحاس أوكسيكلوريد @ 0.25٪ أو Carbendazim @ 0.1٪ فعالة ضد هذا المرض.",
  "Apply aqueous dilutions to trees when new growth occurs to protect flushes of new leaves against transmission of the huanglongbing (HLB) pathogen Candidatus Liberibacter asiaticus by the Asian citrus psyllid (ACP). Retreatment interval is a minimum of 21 days.":
      "ضع تخفيفات مائية على الأشجار عند حدوث نمو جديد لحماية تدفقات الأوراق الجديدة من انتقال مسببات الأمراض (HLB) Candidatus Liberibacter asiaticus بواسطة الحمضيات الآسيوية (ACP). فترة التراجع هي 21 يومًا على الأقل.",
  "Bacterial spot overwinters in bark cracks, near buds, and in leaf scars. Dormant sprays are essential in the fall to protect the stems of your peach tree. Use a copper-based fungicide spray on the tree’s leaves when they begin to fall":
      "البقع البكتيرية في الشتاء في شقوق اللحاء، بالقرب من البراعم، وفي ندوب الأوراق. البخاخات الخاملة ضرورية في الخريف لحماية سيقان شجرة الخوخ. استخدم رذاذ مبيدات الفطريات القائم على النحاس على أوراق الشجرة عندما تبدأ في السقوط",
  "Copper sprays can be used to control bacterial leaf spot, but they are not as effective when used alone on a continuous basis. Thus, combining these sprays with a plant resistance inducer, such as Regalia or Actigard, can provide good protection from the disease.":
      "يمكن استخدام بخاخات النحاس للتحكم في بقعة الأوراق البكتيرية، لكنها ليست فعالة عند استخدامها بمفردها بشكل مستمر. وبالتالي، فإن الجمع بين هذه البخاخات ومحفز مقاومة النبات، مثل Regalia أو Actigard، يمكن أن يوفر حماية جيدة من المرض.",
  "Early blight can be minimized by maintaining optimum growing conditions, including proper fertilization, irrigation, and management of other pests. Grow later maturing, longer season varieties. Fungicide application is justified only when the disease is initiated early enough to cause economic loss.":
      "يمكن تقليل الآفة المبكرة من خلال الحفاظ على ظروف النمو المثلى، بما في ذلك الإخصاب المناسب والري وإدارة الآفات الأخرى. تنمو لاحقًا، أصناف الموسم الأطول. لا يمكن تبرير تطبيق مبيدات الفطريات إلا عندما يبدأ المرض في وقت مبكر بما يكفي للتسبب في خسارة اقتصادية.",
  "Late blight is controlled by eliminating cull piles and volunteer potatoes, using proper harvesting and storage practices, and applying fungicides when necessary. Air drainage to facilitate the drying of foliage each day is important.":
      "يتم التحكم في الآفة المتأخرة عن طريق القضاء على أكوام الإعدام والبطاطا التطوعية، باستخدام ممارسات الحصاد والتخزين المناسبة، وتطبيق مبيدات الفطريات عند الضرورة. من المهم تصريف الهواء لتسهيل تجفيف أوراق الشجر كل يوم.",
  "There are a number of organic options available as well as traditional fungal sprays. Sulfur and “Stylet” oil are effective products for powdery mildew control. Fixed copper fungicides have also shown results in managing powdery mildew. Neem oil is also an effective combatant for managing powdery mildew.":
      "هناك عدد من الخيارات العضوية المتاحة بالإضافة إلى البخاخات الفطرية التقليدية. يعتبر زيت الكبريت و «الستايليت» منتجات فعالة للتحكم في مسحوق العفن. كما أظهرت مبيدات فطريات النحاس الثابتة نتائج في إدارة مسحوق العفن. زيت النيم هو أيضًا مقاتل فعال لإدارة مسحوق العفن.",
  "Remove infected leaves and debris. Increase air circulation to encourage leaf drying. Consider resistant cultivars. Use fungicides if disease becomes severe.":
      "إزالة الأوراق المصابة والحطام. زيادة دوران الهواء لتشجيع تجفيف الأوراق. ضع في اعتبارك الأصناف المقاومة. استخدم مبيدات الفطريات إذا أصبح المرض شديدًا.",
};
