const Map<String, String> en = {
  'login': 'Log in',
  "nodata": "No Data Found",
  'useremail': 'User Email',
  'userpassword': 'User Password',
  'forgetpassword': 'Forget Password',
  'welcomtothefarm': 'Welcom To The Farm',
  'thefarmer': 'The Farmer',
  'myfarm': 'My Farm',
  "test": "Test",
  'farms': 'Farms',
  'detect': 'Detect',
  'menu': 'Menu',
  'acount': 'Acount',
  'setting': 'Setting',
  'help': 'Help',
  "know_the_treatment": "treatment",
  "information": "Information About Us",
  "feedback": "Feedback",
  'Hello in Plantera': 'Hello in Plantera',
  'camera': 'Camera',
  'device': 'Device',
  'upload': 'Upload',
  'farm1': 'Farm 1',
  'farm2': 'Farm 2',
  'farm3': 'Farm 3',
  'farm4': 'Farm 4',
  'farm5': 'Farm 5',
  'farm6': 'Farm 6',
  'farm7': 'Farm 7',
  'farm8': 'Farm 8',
  'farm9': 'Farm 9',
  'farm10': 'Farm 10',
  'farm11': 'Farm 11',
  'farm12': 'Farm 12',
  'temperature': 'Temperature',
  'airhumidity': 'Air Humidity',
  'soilmoisture': 'Soil Moisture',
  'predictgrowth': 'Predict growth',
  'acountinfo': 'Acount Info',
  'username': 'User Name',
  'password': 'Password',
  'phone': 'Phone',
  'location': 'Location',
  'logout': 'Log Out',
  'myprofile': 'My Profile',
  'language': 'Language',
  'darkmode': 'Dark Mode',
  "tomatoes": 'tomatoes',
  "potatoes": 'Potatoes',
  "lettuce": "Lettuce",
  "corn": "Corn",
  "carrots": "Carrots",
  "selectedone": "Selected One",
  'selectedplant': 'Selected Plant',
  "selected language": "Language",
  'withemail': 'With Email',
  "switch": "Switch",
  'withphonenumber': 'With Phone Number',
  'makeselection!': 'Make Selection!',
  'selectoneoftheoptiongivenbelowtoresetyourpassword':
      'Select one of the options given below to reset your password',
  'next': 'Next',
  'email': 'E-mail',
  "info":
      "This program is a smart farm system to take care of the plant by knowing the humidity and temperature of the air and knowing the soil moisture. If the moisture is low for a specific plant, the water motor is operated through the smart irrigation system until it reaches the required humidity. The amount of crop produced in the season can also be predicted. If the plant is sick or not, through the machine learning model and suggesting a treatment. The program is accessed via an email that the user takes from the company responsible for the project. We can be contacted via the web page.",
  'back': 'Back',
  'wehavesentyouemailtorecoverpassword':
      'we have sent you email to recover password',
  'pleasecheckyouremail': 'please check your email',
  'thereiserrorinyouremail': 'there is error in your email',
  'Sucessfulllogin': 'Sucessful login',
  'Hi': 'Hi ',
  'usernameunknown': 'Username unknown',
  'tryanthorone': 'Try another one',
  'resetpassword': 'Reset Password',
  "wait": "Wait",
  "loading": "Loading....",
  "change": "Change",
  'textformisempty': 'TextField Is Empty',
  'youshouldwriteanumber': 'You Should Write A number',
  "acidity": "Acidity",
  "fertilizer": "Fertilizer",
  "passwordunknown": "Wrong Password",
  "It will rany today": "it's raining",
  'thenumberisoutofrange': 'The Number Is out of range',
  'youshouldwriteanumber<100': 'The Number should be [0:100]',
  'youshouldwriteanumber<14': 'The Number should be [0:14]',
  "disease is : ": "Disease is : ",
  'Apple___Apple_scab': 'Apple scab',
  'Apple___Black_rot': 'Black rot (Apple)',
  'Apple___Cedar_apple_rust': 'Cedar Apple Rust',
  'Apple___healthy': 'Apple healthy',
  'Blueberry___healthy': 'Blueberry healthy',
  'Cherry_(including_sour)___Powdery_mildew':
      'Powdery mildew (including sour Cherry)',
  'Cherry_(including_sour)___healthy': ' healthy (including sour Cherry)',
  'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot':
      'leaf spot Gray leaf spot (Corn)',
  'Corn_(maize)__Common_rust': 'Corn Common rust',
  'Corn_(maize)___Northern_Leaf_Blight': 'Corn Northern Leaf Blight',
  'Corn_(maize)___healthy': 'Corn healthy',
  'Grape___Black_rot': 'Grape Black rot',
  'Grape___Esca_(Black_Measles)': 'Black Measles (Grape )',
  "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)":
      'Grape Leaf blight (Isariopsis Leaf Spot)',
  'Grape___healthy': 'Grape healthy',
  'Orange___Haunglongbing_(Citrus_greening)': 'Citrus greening (Orange)',
  'Peach___Bacterial_spot': "Peach Bacterial spot",
  'Peach___healthy': 'Peach healthy',
  'Pepper,_bell___Bacterial_spot': 'Bacterial spot(Pepper )',
  'Pepper,_bell___healthy': 'Healthy pepper',
  'Potato___Early_blight': ' Early blight (Potato)',
  'Potato___Late_blight': 'Late blight (Potato)',
  'Potato___healthy': 'Potato healthy',
  'Raspberry___healthy': 'Raspberry healthy',
  'Soybean___healthy': 'Soybean healthy',
  'Squash___Powdery_mildew': 'Powdery mildew (Squash)',
  'Strawberry___Leaf_scorch': 'Strawberry Leaf scorch',
  'Strawberry___healthy': 'Strawberry healthy',
  'Tomato___Bacterial_spot': 'Bacterial spot(Tomato)',
  'Tomato___Early_blight': ' Early blight (Tomato)',
  'Tomato___Late_blight': 'Late blight (Tomato)',
  'Tomato___healthy': 'Tomato healthy',
  'Tomato___Leaf_Mold': 'Tomato Leaf Mold',
  'Tomato___Septoria_leaf_spot': 'Tomato leaf spot',
  'Tomato___Spider_mites Two-spotted_spider_mite':
      ' Two-spotted spider mite (Tomato)',
  'Tomato___Target_Spot': 'Target Spot (Tomato )',
  'Tomato___Tomato_Yellow_Leaf_Curl_Virus': 'Tomato Yellow Leaf Curl Virus',
  'Tomato___Tomato_mosaic_virus': 'Tomato mosaic virus',
  "null": "Loading....",
  "you have an error": "You Have An Error",
  "Warm wet conditions favour the disease such that fungicides are needed to give adequate control. The products to use are chlorothalonil, copper oxychloride or mancozeb. Treatment should start when the first spots are seen and continue at 10-14-day intervals until 3-4 weeks before last harvest.":
      "Warm wet conditions favour the disease such that fungicides are needed to give adequate control. The products to use are chlorothalonil, copper oxychloride or mancozeb. Treatment should start when the first spots are seen and continue at 10-14-day intervals until 3-4 weeks before last harvest.",
  "Fungicides. Foliar fungicides may be applied early in the growing season to corn seedlings as a risk-management tool for northern corn leaf blight and other corn diseases, including anthracnose leaf blight and corn eyespot.":
      "Fungicides. Foliar fungicides may be applied early in the growing season to corn seedlings as a risk-management tool for northern corn leaf blight and other corn diseases, including anthracnose leaf blight and corn eyespot.",
  "Home gardeners who remove all fallen leaves from under their apple trees should experience good control of apple scab. Leaves may be safely composted. Foliar application of a 5% urea solution in autumn just before leaf drop will speed natural decomposition of leaves and help to deactivate the scab fungus.":
      "Home gardeners who remove all fallen leaves from under their apple trees should experience good control of apple scab. Leaves may be safely composted. Foliar application of a 5% urea solution in autumn just before leaf drop will speed natural decomposition of leaves and help to deactivate the scab fungus.",
  "Fungicides with the active ingredient Myclobutanil are most effective in preventing rust. Copper and sulfur products can be used as well. Spray trees and shrubs when flower buds first emerge until spring weather becomes consistently warm and dry.":
      "Fungicides with the active ingredient Myclobutanil are most effective in preventing rust. Copper and sulfur products can be used as well. Spray trees and shrubs when flower buds first emerge until spring weather becomes consistently warm and dry.",
  "Remove and destroy all affected plant parts. For plants growing under cover, increase ventilation and, if possible, the space between plants. Try to avoid wetting the leaves when watering plants, especially when watering in the evening, Copper-based fungicides can be used to control diseases on tomatoes.":
      "Remove and destroy all affected plant parts. For plants growing under cover, increase ventilation and, if possible, the space between plants. Try to avoid wetting the leaves when watering plants, especially when watering in the evening, Copper-based fungicides can be used to control diseases on tomatoes.",
  "Captan and sulfur products are labeled for control of both scab and black rot. A scab spray program including these chemicals may help prevent the frog-eye leaf spot of black rot, as well as the infection of fruit. These sprays will not control or prevent infection of branches.":
      "Captan and sulfur products are labeled for control of both scab and black rot. A scab spray program including these chemicals may help prevent the frog-eye leaf spot of black rot, as well as the infection of fruit. These sprays will not control or prevent infection of branches.",
  "Powdery mildew is managed through a combination of fungicides, starting from petal fall and continuing through pit hardening, and the use of resistant varieties. Many fungicides used for brown rot control are effective against powdery mildew.":
      "Powdery mildew is managed through a combination of fungicides, starting from petal fall and continuing through pit hardening, and the use of resistant varieties. Many fungicides used for brown rot control are effective against powdery mildew.",
  "During the growing season, foliar fungicides can be used to manage gray leaf spot outbreaks. Farmers must consider the cost of the application and market value of their corn before determining if fungicides will be an economical solution to GLS":
      "During the growing season, foliar fungicides can be used to manage gray leaf spot outbreaks. Farmers must consider the cost of the application and market value of their corn before determining if fungicides will be an economical solution to GLS",
  "The best management practice is to use resistant corn hybrids. Fungicides can also be beneficial, especially if applied early when few pustules have appeared on the leaves.":
      "The best management practice is to use resistant corn hybrids. Fungicides can also be beneficial, especially if applied early when few pustules have appeared on the leaves.",
  "Hot water treatment at 122°F for 25 min is effective in reducing bacterial population on the surface and inside the seeds, but may affect seed germination when the temperature is not properly controlled. Rinse seed in clean water immediately after treatments. The seed should be air dried prior to storing.":
      "Hot water treatment at 122°F for 25 min is effective in reducing bacterial population on the surface and inside the seeds, but may affect seed germination when the temperature is not properly controlled. Rinse seed in clean water immediately after treatments. The seed should be air dried prior to storing.",
  "Treatment. Tomatoes that have early blight require immediate attention before the disease takes over the plants. Thoroughly spray the plant (bottoms of leaves also) with Bonide Liquid Copper Fungicide concentrate or Bonide Tomato & Vegetable. Both of these treatments are organic.":
      "Treatment. Tomatoes that have early blight require immediate attention before the disease takes over the plants. Thoroughly spray the plant (bottoms of leaves also) with Bonide Liquid Copper Fungicide concentrate or Bonide Tomato & Vegetable. Both of these treatments are organic.",
  "Spraying fungicides is the most effective way to prevent late blight. For conventional gardeners and commercial producers, protectant fungicides such as chlorothalonil (e.g., Bravo, Echo, Equus, or Daconil) and Mancozeb (Manzate) can be used.":
      "Spraying fungicides is the most effective way to prevent late blight. For conventional gardeners and commercial producers, protectant fungicides such as chlorothalonil (e.g., Bravo, Echo, Equus, or Daconil) and Mancozeb (Manzate) can be used.",
  "Fungicides are very effective for control of Septoria leaf spot and applications are often necessary to supplement the control strategies previously outlined. The fungicides chlorothalonil and mancozeb are labeled for homeowner use":
      "Fungicides are very effective for control of Septoria leaf spot and applications are often necessary to supplement the control strategies previously outlined. The fungicides chlorothalonil and mancozeb are labeled for homeowner use",
  "make 2 applications, approximately 5-7 days apart, to help control immature mites that were in the egg stage and protected during the first application. Alternate between products after 2 applications to help prevent or delay resistance.":
      "make 2 applications, approximately 5-7 days apart, to help control immature mites that were in the egg stage and protected during the first application. Alternate between products after 2 applications to help prevent or delay resistance.",
  "There is no treatment against TYLCV. Control the whitefly population to avoid the infection with the virus.":
      "There is no treatment against TYLCV. Control the whitefly population to avoid the infection with the virus.",
  "Remove all infected plants and destroy them. Do NOT put them in the compost pile, as the virus may persist in infected plant matter. Burn infected plants or throw them out with the garbage. Monitor the rest of your plants closely, especially those that were located near infected plants.":
      "Remove all infected plants and destroy them. Do NOT put them in the compost pile, as the virus may persist in infected plant matter. Burn infected plants or throw them out with the garbage. Monitor the rest of your plants closely, especially those that were located near infected plants.",
  "Remove infected fruit as it is discovered during the growing season. Fungicide application: Correct timing of fungicide application is critical to effective management of black rot because most fungicide are preventative. Apply protectant fungicides from shortly before bloom through 4 weeks after bloom.":
      "Remove infected fruit as it is discovered during the growing season. Fungicide application: Correct timing of fungicide application is critical to effective management of black rot because most fungicide are preventative. Apply protectant fungicides from shortly before bloom through 4 weeks after bloom.",
  "Soak dormant cuttings for 30 mins in hot water at about 50°C. This treatment is not always effective and must therefore be combined with other methods. Some species of Trichoderma have been used to prevent the infection of pruning wounds, basal ends of propagation material, and graft unions.":
      "Soak dormant cuttings for 30 mins in hot water at about 50°C. This treatment is not always effective and must therefore be combined with other methods. Some species of Trichoderma have been used to prevent the infection of pruning wounds, basal ends of propagation material, and graft unions.",
  "Spraying of the grapevines at 3-4 leaf stage with fungicides like Bordeaux mixture @ 0.8% or Copper Oxychloride @ 0.25% or Carbendazim @ 0.1% are effective against this disease.":
      "Spraying of the grapevines at 3-4 leaf stage with fungicides like Bordeaux mixture @ 0.8% or Copper Oxychloride @ 0.25% or Carbendazim @ 0.1% are effective against this disease.",
  "Apply aqueous dilutions to trees when new growth occurs to protect flushes of new leaves against transmission of the huanglongbing (HLB) pathogen Candidatus Liberibacter asiaticus by the Asian citrus psyllid (ACP). Retreatment interval is a minimum of 21 days.":
      "Apply aqueous dilutions to trees when new growth occurs to protect flushes of new leaves against transmission of the huanglongbing (HLB) pathogen Candidatus Liberibacter asiaticus by the Asian citrus psyllid (ACP). Retreatment interval is a minimum of 21 days.",
  "Bacterial spot overwinters in bark cracks, near buds, and in leaf scars. Dormant sprays are essential in the fall to protect the stems of your peach tree. Use a copper-based fungicide spray on the tree’s leaves when they begin to fall":
      "Bacterial spot overwinters in bark cracks, near buds, and in leaf scars. Dormant sprays are essential in the fall to protect the stems of your peach tree. Use a copper-based fungicide spray on the tree’s leaves when they begin to fall",
  "Copper sprays can be used to control bacterial leaf spot, but they are not as effective when used alone on a continuous basis. Thus, combining these sprays with a plant resistance inducer, such as Regalia or Actigard, can provide good protection from the disease.":
      "Copper sprays can be used to control bacterial leaf spot, but they are not as effective when used alone on a continuous basis. Thus, combining these sprays with a plant resistance inducer, such as Regalia or Actigard, can provide good protection from the disease.",
  "Early blight can be minimized by maintaining optimum growing conditions, including proper fertilization, irrigation, and management of other pests. Grow later maturing, longer season varieties. Fungicide application is justified only when the disease is initiated early enough to cause economic loss.":
      "Early blight can be minimized by maintaining optimum growing conditions, including proper fertilization, irrigation, and management of other pests. Grow later maturing, longer season varieties. Fungicide application is justified only when the disease is initiated early enough to cause economic loss.",
  "Late blight is controlled by eliminating cull piles and volunteer potatoes, using proper harvesting and storage practices, and applying fungicides when necessary. Air drainage to facilitate the drying of foliage each day is important.":
      "Late blight is controlled by eliminating cull piles and volunteer potatoes, using proper harvesting and storage practices, and applying fungicides when necessary. Air drainage to facilitate the drying of foliage each day is important.",
  "There are a number of organic options available as well as traditional fungal sprays. Sulfur and “Stylet” oil are effective products for powdery mildew control. Fixed copper fungicides have also shown results in managing powdery mildew. Neem oil is also an effective combatant for managing powdery mildew.":
      "There are a number of organic options available as well as traditional fungal sprays. Sulfur and “Stylet” oil are effective products for powdery mildew control. Fixed copper fungicides have also shown results in managing powdery mildew. Neem oil is also an effective combatant for managing powdery mildew.",
  "Remove infected leaves and debris. Increase air circulation to encourage leaf drying. Consider resistant cultivars. Use fungicides if disease becomes severe.":
      "Remove infected leaves and debris. Increase air circulation to encourage leaf drying. Consider resistant cultivars. Use fungicides if disease becomes severe.",
};
